# Generated by Django 3.2.13 on 2023-03-06 22:53

from django.db import migrations, models
import realDealz.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('G', models.CharField(default='Action', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P', models.CharField(default='PC', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sources', models.URLField(default='https://www.google.com/')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('title', models.CharField(default='Empty Game', help_text='Give title', max_length=100)),
                ('price', models.CharField(default='-1', max_length=20)),
                ('game_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('genre', models.ManyToManyField(default=realDealz.models.DefaultGenres, help_text='Select Game genres', to='realDealz.Genre')),
                ('platform', models.ManyToManyField(default=realDealz.models.DefaultPlatforms, help_text='Select Game platforms', to='realDealz.Platform')),
                ('vendors', models.ManyToManyField(default=realDealz.models.DefaultSellers, help_text='Links to all vendors', to='realDealz.Seller')),
            ],
        ),
    ]
