# Generated by Django 3.2.13 on 2023-03-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realDealz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
