# Generated by Django 4.1.7 on 2023-04-25 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realDealz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='link',
        ),
    ]
