# Generated by Django 4.1.7 on 2023-03-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realDealz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cover',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
    ]
