# Generated by Django 4.1.7 on 2023-04-07 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realDealz', '0002_game_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.IntegerField(default='-1', max_length=20),
        ),
    ]
