# Generated by Django 3.2.13 on 2023-03-06 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realDealz', '0002_auto_20230223_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='price',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='title',
            field=models.CharField(default='Empty Game', max_length=100),
        ),
    ]
