# Generated by Django 3.2.13 on 2023-03-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realDealz', '0002_alter_game_game_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_id',
            new_name='appid',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='game',
            name='average_2weeks',
            field=models.CharField(default='-1', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='average_forever',
            field=models.CharField(default='-1', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='discount',
            field=models.CharField(default='-1', max_length=20),
        ),
        migrations.AddField(
            model_name='game',
            name='negative',
            field=models.CharField(default='-1', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='positive',
            field=models.CharField(default='-1', max_length=100),
        ),
        migrations.AddField(
            model_name='game',
            name='publisher',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
