# Generated by Django 4.1.7 on 2023-04-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realDealz', '0002_remove_game_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='link',
            field=models.URLField(default='https://www.google.com/'),
        ),
    ]
