# Generated by Django 4.1.7 on 2023-04-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realDealz', '0003_game_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='link',
            field=models.URLField(default='https://www.youtube.com/watch?v=dQw4w9WgXcQ'),
        ),
    ]
