# Generated by Django 4.1.7 on 2023-04-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realDealz', '0004_alter_game_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='about',
            field=models.CharField(default='-1', help_text='About game', max_length=100),
        ),
    ]
