# Generated by Django 4.1.7 on 2023-04-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realDealz', '0005_game_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='about',
            field=models.CharField(default='IDK', help_text='About game', max_length=100),
        ),
    ]
