# Generated by Django 4.1.7 on 2023-04-26 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realDealz', '0006_alter_game_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameSite',
            field=models.URLField(default='https://www.google.com'),
        ),
    ]
