# Generated by Django 4.1.7 on 2023-04-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realDealz', '0007_game_gamesite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gameSite',
            field=models.URLField(default='https://www.youtube.com/watch?v=dQw4w9WgXcQ'),
        ),
    ]
