# Generated by Django 4.1.7 on 2023-04-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realDealz', '0009_remove_game_gamesite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='link',
            field=models.URLField(default='google.com'),
        ),
    ]
