# Generated by Django 4.1.7 on 2023-05-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realDealz', '0010_alter_game_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='link',
            field=models.URLField(default='https://www.google.com'),
        ),
    ]
