# Generated by Django 4.1.7 on 2023-05-01 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realDealz', '0011_alter_game_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='link',
            field=models.CharField(default='https://www.google.com', max_length=200),
        ),
    ]
