# Generated by Django 4.1.7 on 2023-05-03 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realDealz', '0012_alter_game_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(default='Unknown', help_text='Select Game genres', to='realDealz.genre'),
        ),
    ]
