# Generated by Django 4.1.7 on 2023-05-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realDealz', '0015_remove_game_genre_game_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='genre',
        ),
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.CharField(default='IDK', help_text='genre', max_length=100),
        ),
    ]
