name: Django

on: [push, pull_request]

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        cd app/
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd app/
        python manage.py test

  Linting: 
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    steps: 
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          cd app/
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint pylint-django
      - name: Analysing the code with pylint
        run: |
          pylint --errors-only --load-plugins pylint_django \
          --django-settings-module=realDealz.settings \
          $(git ls-files '*.py')